BEGIN TRANSACTION;
CREATE TABLE "USERS" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`MAIL`	TEXT NOT NULL UNIQUE,
	`PASSWORD`	TEXT NOT NULL,
	`ROLE`	INTEGER NOT NULL,
	`MANAGER_ID`	INTEGER NOT NULL
);
INSERT INTO `USERS` VALUES (1,'qauser','qauser',0,1);
CREATE TABLE `LOCATIONS` (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`LATITUDE`	REAL NOT NULL,
	`LONGITUDE`	REAL
);
CREATE TABLE "CARS" (
	`ID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`MANAGER_ID`	INTEGER NOT NULL,
	`LICENCE_NUMBER`	TEXT NOT NULL UNIQUE,
	`MILEAGE`	INTEGER NOT NULL,
	`LAST_KNOWN_LOCATION_ID`	INTEGER,
	`LAST_UPDATE_FROM_FIELD_DATE`	TEXT,
	`LAST_REVISION_DATE`	TEXT NOT NULL,
	FOREIGN KEY(`MANAGER_ID`) REFERENCES `USER`(`ID`),
	FOREIGN KEY(`LAST_KNOWN_LOCATION_ID`) REFERENCES LOCATIONS(ID)
);
INSERT INTO `CARS` VALUES (1,1,'CT 19 TBI',178000,NULL,NULL,'06-10-2015-00-00');
COMMIT;
